version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/kltn
permissions:
   - object: /var/www/html/kltn
     mode: 755
hooks:
  BeforeInstall:
    - location: scripts/removeProject.sh
  AfterInstall:
    - location: scripts/composerInstall.sh